# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE*
- SECURITY.md
- CNAME
- "*.tmp"
- Gemfile
- Gemfile.lock
- gcweb-jekyll.gemspec
- .jekyll-cache
- node_modules
- vendor/

# 2. Installed Gems

# 3. Gem settings

# 4. Jekyll settings
compress_html:
  clippings: all
  comments:
  ignore:
    envs: []
  blanklines: true
  profile: false
quiet: false
timezone: America/Toronto # Timezone for blog posts and alike
verbose: false

# 5. Collections

# 6. Jekyll collections settings
collections:
  pages:
    output: true
    permalink: /:path
  layout:
    name: home
    values:
      altLangPrefix: home
      layout: page
      pageclass: home

# 7. Site settings
analytics_adobe: ""
#assets: "https://wet-boew.github.io/themes-dist/GCWeb"
baseurl: ""

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      share: true
      nomenu: true
  # These two setup the lang to be automagically set per the page location
  - scope:
      path: "_pages/en"
    values:
      lang: "en"
      creator: Shared Services Canada
  - scope:
      path: "_pages/fr"
    values:
      lang: "fr"
      creator: Services partagés Canada
  # These two setup the section and breadcrumbs for the tutorials pages
  - scope:
      path: "_pages/en/tutorials"
    values:
      section: tutorials
      breadcrumbs:
        - title: Tutorials
          link: /en/tutorials/
  - scope:
      path: "_pages/fr/tutoriels"
    values:
      section: tutorials
      breadcrumbs:
        - title: Tutoriels
          link: /fr/tutoriels/

encoding: utf-8 # Make sure the encoding is right
email: "scienceai-iascience@ssc-spc.gc.ca"
#repo: "https://github.com/wet-boew/gcweb-jekyll"
repository: SSCLaunchPad/ssclaunchpad.github.io

#theme: gcweb-jekyll
#title: "GCWeb Jekyll" # Site name or title

plugins:
  - jekyll-last-modified-at
  - jekyll-remote-theme

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%Y-%m-%d'

remote_theme: https://github.com/wet-boew/gcweb-jekyll

global:
  breadcrumbs:
    en:
      - title: "SSC"
        link: "https://www.canada.ca/en/shared-services.html"
      - title: "GC Cloud One"
        link: "https://hosting-services-hebergement.canada.ca/s/cloud-services?language=en_US"
      - title: "LaunchPad"
        link: "https://hosting-services-hebergement.canada.ca/s/gc-cloud-one-launchpad?language=en_US"
      - title: "HOME"
        link: "/en/"
    fr:
      - title: "SPC"
        link: "https://www.canada.ca/fr/services-partages.html"
      - title: "Service infonuagique unifié du GC"
        link: "https://hosting-services-hebergement.canada.ca/s/cloud-services?language=fr"
      - title: "Rampe de lancement"
        link: "https://hosting-services-hebergement.canada.ca/s/gc-cloud-one-launchpad?language=fr"
      - title: "ACCUEIL"
        link: "/fr/"